version: "3"
services:
    nginx:
        image: nginx:latest
        ports:
            - "80:80"
            - "443:443"
        volumes:
            - .:/code
            - ./deployments:/etc/nginx/conf.d
            - /etc/letsencrypt:/etc/letsencrypt:ro
        depends_on: 
            - web
    web:
        build:
            context: .
            dockerfile: Dockerfile
        command: gunicorn config.wsgi:application --bind 0.0.0.0:8000
        volumes:
            - .:/code
        ports:
            - "8000:8000"
        expose:
            - "8000"
        
        
